export const projectId = "xabymxlzpwrpgmowaspo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhYnlteGx6cHdycGdtb3dhc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjMxMzksImV4cCI6MjA4NDczOTEzOX0.ObUVI2jvrGDqKz2mK9PzBE6SfDa9Kp5zph9BaPucZQ0"
